FROM alpine:3.15.11

COPY ./nginx-1.26.1.tar.gz /root

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN apk update && apk add --no-cache build-base && \
    apk add --no-cache pcre pcre-dev && \
    apk add --no-cache zlib zlib-dev && \
    apk add --no-cache openssl openssl-dev && \
    apk add --no-cache linux-headers && \
    tar zxf /root/nginx-1.26.1.tar.gz -C /root && \
    cd /root/nginx-1.26.1 && \
    ./configure \
    --prefix=/etc/nginx \
    --sbin-path=/usr/sbin/nginx \
    --conf-path=/etc/nginx/nginx.conf \
    --error-log-path=/var/log/nginx/error.log \
    --http-log-path=/var/log/nginx/access.log \
    --pid-path=/var/run/nginx.pid \
    --lock-path=/var/run/nginx.lock \
    --http-client-body-temp-path=/var/cache/nginx/client_temp \
    --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
    --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
    --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
    --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
    --user=root \
    --group=root \
    --with-file-aio \
    --with-threads \
    --with-http_addition_module \
    --with-http_auth_request_module \
    --with-http_dav_module \
    --with-http_flv_module \
    --with-http_gunzip_module \
    --with-http_gzip_static_module \
    --with-http_mp4_module \
    --with-http_random_index_module \
    --with-http_realip_module \
    --with-http_secure_link_module \
    --with-http_slice_module \
    --with-http_ssl_module \
    --with-http_stub_status_module \
    --with-http_sub_module \
    --with-http_v2_module \
    --with-mail \
    --with-mail_ssl_module \
    --with-stream \
    --with-stream_realip_module \
    --with-stream_ssl_module \
    --with-stream_ssl_preread_module && \
    make -j4 -l4 && make install && \
    mkdir -p /var/cache/nginx/client_temp && \
    apk del build-base pcre-dev zlib-dev openssl-dev linux-headers && \
    rm -rf /var/cache/apk/* /root/nginx-1.26.1.tar.gz /root/nginx-1.26.1

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
